formatters:
  enable:
    - gofumpt
    - goimports

  exclusions:
    generated: strict

  settings:
    goimports:
      local-prefixes:
        - github.com/prometheus/promu

issues:
  max-issues-per-linter: 0

  max-same-issues: 0

linters:
  disable:
    - errcheck
    - unused

  enable:
    - errorlint
    - gocritic
    - revive

  exclusions:
    generated: strict

    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

  settings:
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true

version: "2"
