formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/prometheus/promu
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  disable:
    - errcheck
    - unused
  enable:
    - errorlint
    - gocritic
    - revive
  exclusions:
    generated: strict
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    warn-unused: true
  settings:
    revive:
      # By default, revive will enable only the linting rules that are named in the configuration file.
      # So, it's needed to explicitly enable all required rules here.
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
        - name: blank-imports
        - name: comment-spacings
        - name: context-as-argument
          arguments:
            # Allow functions with test or bench signatures.
            - allowTypesBefore: '*testing.T,testing.TB'
        - name: context-keys-type
        - name: dot-imports
        - name: early-return
          arguments:
            - preserveScope
        # A lot of false positives: incorrectly identifies channel draining as "empty code block".
        # See https://github.com/mgechev/revive/issues/386
        - name: empty-block
          disabled: true
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
          arguments:
            - preserveScope
        - name: package-comments
          # TODO(beorn7): Currently, we have a lot of missing package doc comments. Maybe we should have them.
          disabled: true
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
          arguments:
            - preserveScope
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: unused-parameter
        - name: var-declaration
        - name: var-naming
version: "2"
