go:
    # Whenever the Go version is updated here,
    # .circle/config.yml should also be updated.
    version: 1.20
repository:
    path: github.com/prometheus/promu
build:
    tags:
      all: [netgo, static_build]
      windows: [static_build]
    flags: -a
    ldflags: |
        -s
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - NOTICE

