verbose: false
go:
    version: 1.12.0
    cgo: false
repository:
    path: github.com/prometheus/prometheus
build:
    prefix: .
    binaries:
        - name: prometheus
          path: ./cmd/prometheus
        - name: promtool
          path: ./cmd/promtool
    flags: -a -tags netgo
    ldflags: |
        -s
        -X {{repoPath}}/version.Version={{.Version}}
        -X {{repoPath}}/version.Revision={{.Revision}}
        -X {{repoPath}}/version.Branch={{.Branch}}
        -X {{repoPath}}/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    prefix: .
    files:
        - consoles
        - console_libraries
        - documentation/examples/prometheus.yml
        - LICENSE
        - NOTICE
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - darwin/amd64
        - darwin/386
        - windows/amd64
        - windows/386
        - freebsd/amd64
        - freebsd/386
        - openbsd/amd64
        - openbsd/386
        - netbsd/amd64
        - netbsd/386
        - dragonfly/amd64
        - linux/arm
        - linux/arm64
        - freebsd/arm
        - openbsd/arm
        - netbsd/arm
        - aix/ppc64
        - linux/ppc64
        - linux/ppc64le
        - linux/mips64
        - linux/mips64le
        - linux/s390x
